"""revision-4

Revision ID: 0c716a0a5c97
Revises: aaed57ecfd0e
Create Date: 2026-01-06 11:54:30.959156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c716a0a5c97'
down_revision: Union[str, Sequence[str], None] = 'aaed57ecfd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_constraint(op.f('owner_of_product'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'User', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('owner_of_product'), 'products', 'User', ['owner_id'], ['id'])
    op.drop_table('Votes')
    # ### end Alembic commands ###
